baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Tracer - トレーサー'
theme = 'cactus'

[params]
colortheme = 'dark'
description = 'I write about: A.I, AR and Health. Bio Engineer, iOS Dev, Melomaniac, Sound & Hardware hacker. (TUM, ITESM) (Munich, GDL)'

[[menu.main]]
name = 'Writtings'
url = '/posts'
weigth =  1

[[menu.main]]
name = 'Pr0jects'
url = '/projects'
weight = 1

[[menu.main]]
name = 'Home'
url = '/'
weigth = 1

[[menu.main]]
name = 'About'
url = '/about'
weigth =  1


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
